---
# Source: netdata/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netdata
  labels:
    app: netdata
    chart: netdata-3.7.141
    release: netdata
    heritage: Helm
rules:
  - apiGroups: [""]
    resources:
      - "pods"           # used by sd, go.d/k8s_state, netdata (cgroup-name.sh, get-kubernetes-labels.sh)
      - "services"       # used by sd
      - "configmaps"     # used by sd
      - "secrets"        # used by sd
      - "nodes"          # used by go.d/k8s_state
      - "nodes/metrics"  # used by go.d/k8s_kubelet when querying Kubelet HTTPS endpoint
      - "nodes/proxy"    # used by netdata (cgroup-name.sh) when querying Kubelet /pods endpoint
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["apps"]
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["batch"]
    resources:
      - "cronjobs"
      - "jobs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: [""]
    resources:
      - "namespaces"  # used by go.d/k8s_state, netdata (cgroup-name.sh, get-kubernetes-labels.sh)
    verbs:
      - "get"
