---
# Source: netdata/templates/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: netdata
    chart: netdata-3.7.141
    release: netdata
    heritage: Helm
  name: netdata
  namespace: monitoring
