apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instance.name }}-meta
  namespace: {{ .Values.instance.name }}
spec:
  selector:
    app: {{ .Values.instance.name }}-meta
  ports:
  - port: {{ .Values.meta.port }}
    targetPort: {{ .Values.meta.port }}
