
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.instance.name }}-postgres-pvc
  namespace: {{ .Values.instance.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  storageClassName: {{ .Values.postgres.storage.className }}
