
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instance.name }}-studio
  namespace: {{ .Values.instance.name }}
spec:
  selector:
    app: {{ .Values.instance.name }}-studio
  ports:
  - port: {{ .Values.studio.port }}
    targetPort: {{ .Values.studio.port }}
