/**
 * Configuration for the template repos update script
 */

export interface TemplateConfig {
  // Template information
  templateOwner: string
  templateRepo: string

  // GitHub token (required)
  githubToken: string | undefined

  // Branch and PR configuration
  branchName: string
  prTitle: string

  // Files to update from template
  filesToUpdate: string[]

  // Pull Request message
  prBody: string

  // Repos to update (manual list)
  reposToUpdate: Array<{
    owner: string
    name: string
    defaultBranch?: string
  }>

  // Advanced options
  options: {
    // Maximum number of repos to process
    maxRepos: number

    // Delay between API requests (in ms)
    requestDelay: number

    // Show debug details
    debug: boolean

    // Ignore repos with errors
    ignoreErrors: boolean

    // Create issues for failures
    createIssuesForFailures: boolean
  }
}

export const config: TemplateConfig = {
  // Template information
  templateOwner: process.env.TEMPLATE_OWNER || 'your-username',
  templateRepo: process.env.TEMPLATE_REPO || 'your-template',

  // GitHub token (required)
  githubToken: process.env.TOKEN,

  // Branch and PR configuration
  branchName: 'update-from-template',
  prTitle: '🔄 Update from template',

  // Files to update from template
  filesToUpdate: [
    'client/components/atoms/PWAButton.tsx',
    'middleware.ts',
    'public/manifest.json',
    'app/sw.ts',
    'package.json',
  ],

  // Repos to update (manual list)
  reposToUpdate: [
    // Add your repos here
    // Example:
    // { owner: 'koala819', name: 'Eduroots-Example-Repo', defaultBranch: 'main' },
  ],

  // Pull Request message
  prBody: `
## 🔄 Automatic update from template

This Pull Request updates your repo with the latest changes from the template.

### 📋 Included changes:
- ✅ Fixed automatic PWA installation
- ✅ Improved middleware for static files
- ✅ Performance optimizations
- ✅ Support for beforeinstallprompt event

### 🚀 Automatic PWA Installation
The \`beforeinstallprompt\` event is now properly handled to trigger native browser installation.

### 🔧 How to test:
1. Click on the "Install application" button
2. Native browser installation should trigger
3. On iOS, manual instructions are displayed

### 📝 Notes:
- This update is compatible with previous versions
- No additional configuration required
- Test in development mode with \`npm run dev\`

### 🔄 Automatic updates
This script can be run regularly to keep your repos up to date:
\`\`\`bash
npm run update-template-repos
\`\`\`

---

*This PR was automatically generated by the template update script.*
  `.trim(),

  // Advanced options
  options: {
    // Maximum number of repos to process
    maxRepos: 100,

    // Delay between API requests (in ms)
    requestDelay: 1000,

    // Show debug details
    debug: process.env.DEBUG === 'true',

    // Ignore repos with errors
    ignoreErrors: false,

    // Create issues for failures
    createIssuesForFailures: false,
  },
}
