---
# Source: netdata/templates/parent/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-parent
  namespace: default
  labels:
    app: netdata
    chart: netdata-3.7.141
    release: netdata
    heritage: Helm
data:
    
  health: |
        SEND_EMAIL="NO"
        SEND_SLACK="YES"
        SLACK_WEBHOOK_URL=""
        DEFAULT_RECIPIENT_SLACK=""
  netdata: |
        [global]
          hostname = netdata-parent
        [db]
          mode = dbengine
      
        [plugins]
          cgroups = no
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = no
          go.d = no
          node.d = no
          apps = no
          proc = no
          idlejitter = no
          diskspace = no
  stream: |
        [11111111-2222-3333-4444-555555555555]
          enabled = yes
          history = 3600
          default memory mode = dbengine
          health enabled by default = auto
          allow from = *
