name: 🔄 Update Template Repos

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update even if no changes detected'
        required: false
        default: false
        type: boolean

  # Automatic trigger on push to main
  push:
    branches: [main]
    paths:
      - 'client/components/atoms/PWAButton.tsx'
      - 'middleware.ts'
      - 'public/manifest.json'
      - 'app/sw.ts'
      - 'package.json'

  # Weekly trigger (Sunday at 9am)
  schedule:
    - cron: '0 9 * * 0'

jobs:
  update-template-repos:
    name: 🔄 Template repos update
    runs-on: ubuntu-latest

    # Avoid concurrent executions
    concurrency:
      group: update-template-repos
      cancel-in-progress: false

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔍 Check for changes
        id: check-changes
        run: |
          # Check if there are changes in PWA files
          if git diff --name-only HEAD~1 | grep -E "(PWAButton|middleware|manifest|sw\.ts)" > /dev/null; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "✅ Changes detected in PWA files"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No changes in PWA files"
          fi

      - name: 🔄 Update template repos
        if: steps.check-changes.outputs.has_changes == 'true' || github.event.inputs.force_update == 'true'
        run: |
          echo "🚀 Starting automatic update"
          echo "📋 Template: ${{ github.repository }}"
          echo "🔑 Token configured: ${{ secrets.TOKEN != '' }}"

          # Run the update script
          npm run update-template-repos
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TEMPLATE_OWNER: ${{ github.repository_owner }}
          TEMPLATE_REPO: ${{ github.event.repository.name }}
          DEBUG: ${{ github.event.inputs.force_update == 'true' }}

      - name: ✅ Success
        if: steps.check-changes.outputs.has_changes == 'true' || github.event.inputs.force_update == 'true'
        run: |
          echo "🎉 Template repos update completed successfully!"
          echo "📅 Date: $(date)"
          echo "🔗 Commit: ${{ github.sha }}"

      - name: ⏭️ Skip (no changes)
        if: steps.check-changes.outputs.has_changes == 'false' && github.event.inputs.force_update != 'true'
        run: |
          echo "⏭️ No changes detected, update skipped"
          echo "💡 Use 'force_update: true' to force update"

      - name: 📊 Final report
        if: always()
        run: |
          echo "📊 Execution report:"
          echo "  - Workflow: ${{ github.workflow }}"
          echo "  - Trigger: ${{ github.event_name }}"
          echo "  - Repository: ${{ github.repository }}"
          echo "  - Commit: ${{ github.sha }}"
          echo "  - Date: $(date)"
